### PR TITLE
Add to .gitignore package-lock.json unique user

### PR DESCRIPTION
**Pull request by Linedev-Web**
Add to .gitignore package-lock.json unique user

### CODE REVIEW

**Comment by z4q** [comment]
better not to mess with package-lock just follow the dev using yarn

**Comment by Linedev-Web** [comment]
Exactly when we spank the npm install it will generate this file but it's unique by user so it's better to add it in the .gitignore I think.

**Comment by z4q** [comment]
if this project not very dependent with javascript then your PR is valid. i work as js developer so this package-lock or yarn-lock is very important to track plugin usage same as other dev.just let this project dev decide. :)

**Comment by izio38** [comment]
Hi @Linedev-Web. all `locks` file should be gitted. In fact, we want our `packages` version to be the same for person A and for person B.

We'll add the `.lock` file soon, or feel free to open a PR which do this :)

**Pull request closed without merging**
