### PR TITLE
fix(legacy): Resolve version conflict (#1148); tweak event handler in imports; general tweaks

### PR DESCRIPTION
**Pull request by thelindat**
#1118 was resolved (in last pull request)

## Proposed Changes
    - Merged #1148 with resolved conflict (version.json)
    - `esx:setPlayerData` is now only registered on the client when using imports
    - Removed resource name print (FXServer does this now)
    - Store playerPed and isDead in ESX.PlayerData (ped / dead)
    - Start DBSync and PayCheck functions after initializing
    - Removed the callback for esx_skin (not necessary)

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
@thelindat How often is the PlayerData ped updated in this, I see you register the event but do you also trigger it every time there can be a ped change?

**Comment by thelindat** [comment]
> 
> 
> @thelindat How often is the PlayerData ped updated in this, I see you register the event but do you also trigger it every time there can be a ped change?

PlayerPed is checked on death, spawn, when restoring loadout, and as part of the coords update loop (1500ms). If the ped is different than the stored value, save the new value. I can undo it, if you prefer.

**Comment by TasoOneAsia** [comment]
It would be better to do it this way but it is *technically* breaking because customization setups that change the model itself would need to call the event.

**Comment by TasoOneAsia** [comment]
We talked about this in DM's and we had decided that the 1.5 second update time on the ped is enough for third party resources

**Review by TasoOneAsia — APPROVED** [review]

**Pull request merged**
